### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by purpleglow** [sttz/expresso#14]
The command **expresso locations** outputs the locations correctly. 
But "expresso alfred"  returns "Object reference not set to an instance of an object." How can I debug this problem? This is a new computer. On my previous computer when I type "expresso alfred" it returns the JSON as expected.

Because of this error the workflow is not working on the new computer. 

Thank you.

**Comment by sttz** [comment]
You can increase the verbosity by adding `-v` or `-vv` to the arguments.
Then you should get a stack trace with the error, which should help to point to the source of the problem.

**Comment by purpleglow** [comment]
expresso alfred -v
expresso v1.3.0
Log level set to Information
Manifest loaded for com.expressvpn.helper with helper at: /Applications/ExpressVPN.app/Contents/MacOS/expressvpn-browser-helper
Connected to ExpressVPN version 10.12.0
Object reference not set to an instance of an object.
   at sttz.expresso.ExpressoCLI.Alfred()
   at sttz.expresso.ExpressoCLI.Main(String[] args)

**Comment by jiserra** [comment]
I have the same error. Can I help with anything to debug this?
